spring.application.name=Instakilo

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:instakilo}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}

security.jwt.secret-key=4wJdrNoq1Xc3F0XS7U6yIE3KVHLco1I6NziEsDnrYkQ=
security.jwt.expiration-time=3600000